### ISSUE TITLE
Add a publish command

### ISSUE THREAD

**Issue by DominicKramer** [GoogleCloudPlatform/nodejs-repo-tools#118]
I would be nice to have a publish command that we could use to do checks before running `npm publish`.

In particular, there was an issue where the error-reporting library was published but didn't contain a `build` directory.  This appears to be caused by an error in the CircleCI config.

It would be nice if `repo-tools publish` would verify that the files specified in the `files` section of `package.json` exist before running `npm publish` and failing if not.

**Comment by JustinBeckwith** [comment]
We're kinda putting this in bug fix mode only, so it isn't likely this will happen :(
