### ISSUE TITLE
Add Support for a Custom README

### ISSUE THREAD

**Issue by DominicKramer** [GoogleCloudPlatform/nodejs-repo-tools#123]
It would be nice to be able to instruct the scaffolding tool to create a link in the auto-generated README to a secondary file that contains additional manually written information.  The error-reporting and logging-bunyan libraries, for example, have additional manually written information that is useful.

**Comment by DominicKramer** [comment]
Are there any updates on this?  Thanks.

**Comment by alexander-fenster** [comment]
Would be nice to make it possible to override any file, not just a readme.

**Comment by DominicKramer** [comment]
Friendly ping.

**Comment by fhinkel** [comment]
Closing as we're archiving this repository.
