### ISSUE TITLE
Contributors listed in package.json

### ISSUE THREAD

**Issue by fhinkel** [GoogleCloudPlatform/nodejs-repo-tools#127]
`generate all` add contributors to `package.json` *and* `CONTRIBUTORS`. This adds a lot of bloat to `package.json`. Is there an option to only add them to the `CONTRIBUTORS` file?

**Comment by fhinkel** [comment]
cc @JustinBeckwith

**Comment by jmdobry** [comment]
this can be done by changing https://github.com/GoogleCloudPlatform/nodejs-repo-tools/blob/master/src/build_packs/nodejs.js#L157 to `delete json.contributors`.
