### ISSUE TITLE
Remove Node4 and Node9 from circle config

### ISSUE THREAD

**Issue by crwilcox** [GoogleCloudPlatform/nodejs-repo-tools#128]
Templates from 'generate' include Node4 and Node9 which are EOL and should be removed.

**Comment by alexander-fenster** [comment]
It does not belong here. Repo tools don't generate Circle config for now.

**Comment by JustinBeckwith** [comment]
@alexander-fenster ... should it?  Or is this something that should be left to the gapic-generator?

**Comment by theacodes** [comment]
Synthtool should do this, and for that matter, should do everything else this repo currently does.
