### ISSUE TITLE
GOOGLE_CLOUD_PROJECT env var not accepted instead of GCLOUD_PROJECT

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/nodejs-repo-tools#181]
## Expected

Either `GOOGLE_CLOUD_PROJECT` or `GCLOUD_PROJECT` should be accepted as an appropriate env variable for the project.

## Actual

Modifying a test that uses `GOOGLE_CLOUD_PROJECT` instead of `GCLOUD_PROJECT` fails the parent repos' Kokoro tests (`nodejs-getting-started` repo).

```sh
@google-cloud/nodejs-repo-tools/cjs/index.js:283
Must set GCLOUD_PROJECT environment variable!
Value is not truthy:
undefined
```

---

Helps fix https://github.com/GoogleCloudPlatform/nodejs-getting-started/pull/253.

### Source

https://github.com/GoogleCloudPlatform/nodejs-repo-tools/blob/171629c558148014a91ca2531717fef47a50c51a/src/index.js#L275

**Comment by fhinkel** [comment]
Closing as we're archiving this repository.
