### ISSUE TITLE
explore deprecating nodejs-repo-tools

### ISSUE THREAD

**Issue by bcoe** [GoogleCloudPlatform/nodejs-repo-tools#194]
Hey @fhinkel :wave: I'm moving the conversation from https://github.com/googleapis/google-cloud-node/issues/2868:

> nodejs-docs-samples and nodejs-getting-started is still using many of the test commands and things like repo-tools.getRequest() in the test code.

I wonder if we could break the test helpers into their own more target tool, perhaps a library called `test-helpers`?

Could you go into some details about your use-case?

**Comment by fhinkel** [comment]
@bcoe I'm still discovering new ways of how `repo-tools` is used 🤣 

We use it in tests to make http request. `getRequest()` adds some logic based on environment variables. https://github.com/GoogleCloudPlatform/nodejs-getting-started/blob/master/2-structured-data/test/_api-tests.js#L16

And we're using it to run the tests
https://github.com/GoogleCloudPlatform/nodejs-getting-started/blob/master/5-logging/package.json#L27

And I don't even know what that is
https://github.com/GoogleCloudPlatform/nodejs-getting-started/blob/master/5-logging/package.json#L13

We use it to generate the list of contributors, but I haven't updated that in a while and afaik we have more targeted tools for that now?

Ideally, we'd replace all usage of `repo-tools`. The tests shouldn't require special test helpers.

**Comment by fhinkel** [comment]
Related https://github.com/GoogleCloudPlatform/nodejs-getting-started/issues/268

**Comment by RicardoBelchior** [comment]
hi, 

> @bcoe I'm still discovering new ways of how repo-tools is used 🤣
this is good to know :) 

I was following the getting started tutorial (https://cloud.google.com/nodejs/getting-started/tutorial-app) and managed to run and understand most stuff (thank you for the great work!!), until I got to the tests section. 

I'm not a javascript expert and failed to understand what this `nodejs-repo-tools` is doing. Still a mystery to me. That's how I ended up in this ticket. Also not sure how to run/setup the e2e tests. 
Would be nice to have some documentation / samples or add a "test" section on the getting started tutorials.

This could be the wrong place to talk about this. Please take it as a constructive review =)

**Comment by bcoe** [comment]
@RicardoBelchior :wave: sorry for the confusion. At a high level, `nodejs-repo-tools` is a library we maintained that provided a variety of abstractions for working with Node.js repos:

* generating default documentation.
* HTTP requests.

... essentially it was a bit of a kitchen sink.

We will, over time, be replacing references to this repository with practices and libraries that are more common across the JavaScript community, e.g., using `node-fetch` rather than this library for HTTP requests.

**Comment by RicardoBelchior** [comment]
Got it! Thanks for the quick reply. 
Looking forward to it, I'll make sure to keep an eye open to this repo!

**Comment by fhinkel** [comment]
Closing as we're archiving this repository.
