### ISSUE TITLE
npm found 1 high severity vulnerability 

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/nodejs-repo-tools#196]
#### Environment details

  - OS: Mac OS 10.14.4
  - Node.js version: 6.7.0
  - npm version: 6.7.0

#### Steps to reproduce

  1. Tired running   npm init then after npm install node-sass -D
  2. Then i get back the following message

   updated 1 package and audited 550 packages in 9.339s
found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

3. So I run npm audit fix and alerted with this below 

up to date in 0.772s
fixed 0 of 1 vulnerability in 550 scanned packages
  1 vulnerability required manual review and could not be updated

4. So I run npm audit next prompted with this message: 

![Screenshot 2019-04-20 at 12 50 44 pm](https://user-images.githubusercontent.com/46603982/56456905-f505ec00-636a-11e9-87cc-a9006f1e3779.png)

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by fhinkel** [comment]
Closing as we're archiving this repository.
