### ISSUE TITLE
[1.4.17] 'samples test app' does not support URLs properly

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/nodejs-repo-tools#20]
Two problems:
1) `samples test app` does not recognize `url` property values specified in `package.json` (fix likely [somewhere near here](https://github.com/GoogleCloudPlatform/nodejs-repo-tools/blob/master/src/cli/commands/test_commands/app.js#L92-L96)). It _does_ recognize `url` values specified on the command line.
2) The `url` property is absolute. We should probably support relative URLs as well.

**Comment by fhinkel** [comment]
Closing as we're archiving this repository.
