### ISSUE TITLE
Lint command only linting samples

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/nodejs-repo-tools#24]
Hello, this PR merged: https://github.com/GoogleCloudPlatform/google-cloud-node-storage/commit/e40a7a5cd655260477afc5f8e1c4e9654c088988 And it had this effect:

```diff
- "lint": "node_modules/.bin/eslint src/ system-test/ test/",
+ "lint": "repo-tools lint 'samples/**/*.js'",
```

I think we want something like:
```
repo-tools lint samples/ src/ system-test/ test/
```

However, when I run `npm run lint` from the root directory of google-cloud-node-storage, `repo-tools` is not a recognized command. Changing it to `samples` works (kind of):

```
> samples lint samples/ src/ system-test/ test/

lint: Linting files in: C:\Users\sawch\dev\google-cloud-node-storage
lint: Running: semistandard 'samples/' 'src/' 'system-test/' 'test/'
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn semistandard ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

Also, when trying to split Bigtable into its own repo, I realized there are no samples, so the `samples/` directory won't exist in all cases.

**Comment by arnaudbreton** [comment]
Installing `semistandard` globally fixed the issue for us: `npm install -g semistandard` or `yarn global add semistandard` 

It's done in the Travis configuration [here](https://github.com/GoogleCloudPlatform/nodejs-repo-tools/blob/089602a5e02f12fac0f5abbcc81a9b7c5add15a7/.travis.yml#L26) but somehow missing from the project dependencies

**Comment by jmdobry** [comment]
Fixed in GoogleCloudPlatform/google-cloud-node-storage#4

@stephenplusplus Going forward, the lint command should just be: `"lint": "repo-tools lint"`, which will automatically lint _all_ .js files. google-cloud-node-storage was only linting the samples because @lukesneeringer wanted to fix lint errors in other files in a single commit.

In GoogleCloudPlatform/google-cloud-node-storage#4 I added `semistandard` to the `devDependencies`. 

If Bigtable doesn't have samples, then the samples section of the lib's auto-generated readme _should_ be automatically omitted. If that doesn't work then please open an issue. However, adding a `samples/quickstart.js` file to all package repos should be high priority (I can do it for products that don't have a `quickstart.js` sample).

**Comment by stephenplusplus** [comment]
I'm still struggling with this:

```
$ npm run lint

> @google-cloud/storage@1.2.1 lint C:\Users\sawch\dev\google-cloud-node-storage
> repo-tools lint 'samples/**/*.js'

lint: Linting files in: C:\Users\sawch\dev\google-cloud-node-storage
lint: Running: semistandard 'samples/**/*.js'
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn semistandard ENOENT
    at _errnoException (util.js:1041:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:611:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```

**Comment by jmdobry** [comment]
It means `semistandard` could not be found in the path. Can you provide me some repro steps? I just did the following and it worked fine:

<img width="1061" alt="screen shot 2017-09-06 at 8 52 59 pm" src="https://user-images.githubusercontent.com/1213510/30145324-7b12c2c0-9345-11e7-9dab-fea20e8899d5.png">

**Comment by lukesneeringer** [comment]
> google-cloud-node-storage was only linting the samples because @lukesneeringer wanted to fix lint errors in other files in a single commit.

I still want this. Ideally I would like for the process to be:

  * The linter is added, issuing warnings
  * The `repo-migration` branch is merged as part of (we all know what)
  * A subsequent commit is made to get the linter's issues addressed.

My rationale is basically this: The `repo-migration` to `master` PR is already going to be _huge_. It will be even _more huge-er_ if we also have a bunch of linting changes in there.

Thoughts? I am totally willing to be told I am wrong here.

**Comment by stephenplusplus** [comment]
@jmdobry I think this could be a Windows issue. Would it be possible to use [shelljs](https://github.com/shelljs/shelljs) for scripted CLI commands?

For the [lint task](https://github.com/GoogleCloudPlatform/nodejs-repo-tools/blob/ce91f077ed4052cd60268a33ce567620ca471e1d/src/cli/commands/lint.js#L75):

```diff
  const options = {
    cwd: opts.localPath,
    stdio: 'inherit',
+   async: true
  };

+  cmd = `${cmd} ${args.join(' ')`;

-  spawn(cmd, args, options)
+  spawn(cmd, options)
    .on('exit', (code, signal) => {
      if (code !== 0 || signal) {
        error('lint', 'Linting failed.'.red);
        process.exit(code || 1);
      } else {
        log('lint', 'Looks good!'.green);
      }
    });
```

Tested locally, this corrects the issue with locating the `semistandard` executable.

**Comment by jmdobry** [comment]
What if instead of using shelljs, you just add `shell: true` to the `options` passed to `spawn`? Does that fix it for you as well?

**Comment by stephenplusplus** [comment]
Yes, that worked as well!

**Comment by jmdobry** [comment]
woot, I'll fix it in repo tools and cut a release. I'm guessing I need to do this for multiple commands.
