### ISSUE TITLE
Samples readme no longer writes.

### ISSUE THREAD

**Issue by lukesneeringer** [GoogleCloudPlatform/nodejs-repo-tools#51]
The `lib_samples_readme` is no longer able to generate.

**Workaround:** Copy `.cloud-repo-tools.json` from the root of the project into `samples/`.

**Comment by jmdobry** [comment]
Can you point to specific projects where this isn't working?

**Comment by jmdobry** [comment]
I encountered this when the path to the `.cloud-repo-tools.json` file passed to the `--config` option was wrong. Is that what happened here?

**Comment by fhinkel** [comment]
Closing as we're archiving this repository.
