### ISSUE TITLE
Add warn to stubConsole()

### ISSUE THREAD

**Issue by briangranatir** [GoogleCloudPlatform/nodejs-repo-tools#74]
Tools stub console.error and console.log but not console.warn.

#### Steps to reproduce

  1. add the following code to index.js: 
```
console.warn('foo')
```
  2. stub console in sinon tests: 
```
const tools = require(`@google-cloud/nodejs-repo-tools`);
test.beforeEach(tools.stubConsole);
```
  3. run test
  4. note that warning messages are being shown 

Thanks!  We use your library for our own testing more than you could imagine  :)

**Comment by fhinkel** [comment]
Closing as we're archiving this repository.
