### ISSUE TITLE
Automate js-green-licenses

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/nodejs-repo-tools#94]
It would be great to automate this configuration into all `@google-cloud/*` libraries: https://github.com/googleapis/nodejs-common/pull/18/files

cc @jinwoo

**Comment by jmdobry** [comment]
@stephenplusplus For this, you wanting to add `jsgl --local` to the `repo-tools lint` command?

**Comment by stephenplusplus** [comment]
I believe so, if we have a requirement to validate the licenses of the libraries we use from all of our client libs. @alexander-fenster @jinwoo?

**Comment by jinwoo** [comment]
AIUI all the libraries/packages we depend on must have a valid license.

You can do `jsgl --local .` from `repo-tools lint`. But some repos may start to fail once you do that, and each repo should be fixed separately -- by whitelisting packages, using other libraries, etc.

**Comment by jmdobry** [comment]
I'm thinking it would be better to add a `repo-tools check-licenses` command (which could use `jsgl --local .` under the hood for Node.js), that way other languages can add their own license-checking support.

**Comment by stephenplusplus** [comment]
SGTM
